[2024-05-03T17:42:27.224+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-03T17:42:27.239+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dagv3.third_task scheduled__2024-05-01T18:00:00+00:00 [queued]>
[2024-05-03T17:42:27.242+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dagv3.third_task scheduled__2024-05-01T18:00:00+00:00 [queued]>
[2024-05-03T17:42:27.243+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-03T17:42:27.248+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): third_task> on 2024-05-01 18:00:00+00:00
[2024-05-03T17:42:27.252+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'our_first_dagv3', 'third_task', 'scheduled__2024-05-01T18:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/our_first_dag.py', '--cfg-path', '/tmp/tmppiqblp5r']
[2024-05-03T17:42:27.253+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask third_task
[2024-05-03T17:42:27.253+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=437) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-03T17:42:27.253+0000] {standard_task_runner.py:63} INFO - Started process 438 to run task
[2024-05-03T17:42:27.274+0000] {task_command.py:426} INFO - Running <TaskInstance: our_first_dagv3.third_task scheduled__2024-05-01T18:00:00+00:00 [running]> on host 697ad57716e5
[2024-05-03T17:42:27.311+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='our_first_dagv3' AIRFLOW_CTX_TASK_ID='third_task' AIRFLOW_CTX_EXECUTION_DATE='2024-05-01T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-01T18:00:00+00:00'
[2024-05-03T17:42:27.311+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-03T17:42:27.318+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-03T17:42:27.319+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo this is the third task!']
[2024-05-03T17:42:27.324+0000] {subprocess.py:86} INFO - Output:
[2024-05-03T17:42:27.325+0000] {subprocess.py:93} INFO - this is the third task!
[2024-05-03T17:42:27.325+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-03T17:42:27.326+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-03T17:42:27.340+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=our_first_dagv3, task_id=third_task, execution_date=20240501T180000, start_date=20240503T174227, end_date=20240503T174227
[2024-05-03T17:42:27.352+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-03T17:42:27.360+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-03T17:42:27.361+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
