[2024-05-15T10:25:38.303+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T10:25:38.327+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_hdfs.save scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-15T10:25:38.333+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_hdfs.save scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-15T10:25:38.334+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2024-05-15T10:25:38.353+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): save> on 2024-05-10 00:00:00+00:00
[2024-05-15T10:25:38.361+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=742) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T10:25:38.361+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_hdfs', 'save', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/hdfs_dag.py', '--cfg-path', '/tmp/tmpq9lzkcgk']
[2024-05-15T10:25:38.362+0000] {standard_task_runner.py:63} INFO - Started process 769 to run task
[2024-05-15T10:25:38.363+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask save
[2024-05-15T10:25:38.399+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_hdfs.save scheduled__2024-05-10T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-15T10:25:38.452+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_hdfs' AIRFLOW_CTX_TASK_ID='save' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-15T10:25:38.454+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T10:25:38.462+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-15T10:25:38.465+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'hdfs dfs -mkdir /tmp']
[2024-05-15T10:25:38.473+0000] {subprocess.py:86} INFO - Output:
[2024-05-15T10:25:38.474+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: hdfs: command not found
[2024-05-15T10:25:38.475+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-05-15T10:25:38.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T10:25:38.481+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-05-15T10:25:38.484+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_hdfs, task_id=save, execution_date=20240510T000000, start_date=20240515T102538, end_date=20240515T102538
[2024-05-15T10:25:38.489+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task save (Bash command failed. The command returned a non-zero exit code 127.; 769)
[2024-05-15T10:25:38.504+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T10:25:38.513+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T10:25:38.514+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
