[2024-05-16T11:14:22.955+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:14:23.005+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-16T11:14:23.048+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-16T11:14:23.051+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:14:23.161+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_tables> on 2024-05-10 00:00:00+00:00
[2024-05-16T11:14:23.173+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6438) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:14:23.178+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_tables', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '356', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmprbvgn6xw']
[2024-05-16T11:14:23.195+0000] {standard_task_runner.py:91} INFO - Job 356: Subtask import_tables
[2024-05-16T11:14:23.188+0000] {standard_task_runner.py:63} INFO - Started process 6475 to run task
[2024-05-16T11:14:23.343+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [running]> on host 8b94fd4f2665
[2024-05-16T11:14:23.538+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-16T11:14:23.567+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:14:23.586+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:14:23.590+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/products.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category_map.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/report_table.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/rw_transaction_data.sql;\n            ']
[2024-05-16T11:14:23.612+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:14:23.963+0000] {subprocess.py:93} INFO - ERROR 1050 (42S01) at line 8: Table 'customer_profile' already exists
[2024-05-16T11:14:24.326+0000] {subprocess.py:93} INFO - ERROR 1100 (HY000) at line 59: Table 'rw_transaction_500_demo' was not locked with LOCK TABLES
[2024-05-16T11:14:24.328+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-16T11:14:24.329+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:14:24.335+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-16T11:14:24.338+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_tables, task_id=import_tables, execution_date=20240510T000000, start_date=20240516T111423, end_date=20240516T111424
[2024-05-16T11:14:24.346+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 356 for task import_tables (Bash command failed. The command returned a non-zero exit code 1.; 6475)
[2024-05-16T11:14:24.391+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T11:14:24.399+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:14:24.400+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:15:44.319+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:15:44.358+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-16T11:15:44.373+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-16T11:15:44.378+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:15:44.442+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_tables> on 2024-05-10 00:00:00+00:00
[2024-05-16T11:15:44.453+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_tables', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '372', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpe1z7k9by']
[2024-05-16T11:15:44.468+0000] {standard_task_runner.py:91} INFO - Job 372: Subtask import_tables
[2024-05-16T11:15:44.473+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6590) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:15:44.474+0000] {standard_task_runner.py:63} INFO - Started process 6616 to run task
[2024-05-16T11:15:44.520+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_tables scheduled__2024-05-10T00:00:00+00:00 [running]> on host 8b94fd4f2665
[2024-05-16T11:15:44.635+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_tables' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-16T11:15:44.637+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:15:44.650+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:15:44.657+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/products.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category_map.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/report_table.sql;\n            mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/rw_transaction_data.sql;\n            ']
[2024-05-16T11:15:44.670+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:15:45.181+0000] {subprocess.py:93} INFO - ERROR 1050 (42S01) at line 8: Table 'customer_profile' already exists
[2024-05-16T11:15:45.297+0000] {subprocess.py:93} INFO - ERROR 1050 (42S01) at line 25: Table 'rw_transaction_data' already exists
[2024-05-16T11:15:45.300+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-16T11:15:45.302+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:15:45.311+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-16T11:15:45.316+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_tables, task_id=import_tables, execution_date=20240510T000000, start_date=20240516T111544, end_date=20240516T111545
[2024-05-16T11:15:45.331+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 372 for task import_tables (Bash command failed. The command returned a non-zero exit code 1.; 6616)
[2024-05-16T11:15:45.371+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T11:15:45.381+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:15:45.382+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
