[2024-05-04T16:21:45.840+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T16:21:45.853+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.check_space manual__2024-05-04T15:57:32.696548+00:00 [queued]>
[2024-05-04T16:21:45.857+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.check_space manual__2024-05-04T15:57:32.696548+00:00 [queued]>
[2024-05-04T16:21:45.857+0000] {taskinstance.py:2303} INFO - Starting attempt 10 of 14
[2024-05-04T16:21:45.862+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): check_space> on 2024-05-04 15:57:32.696548+00:00
[2024-05-04T16:21:45.866+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3692) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T16:21:45.866+0000] {standard_task_runner.py:63} INFO - Started process 3693 to run task
[2024-05-04T16:21:45.866+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'check_space', 'manual__2024-05-04T15:57:32.696548+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpdfjrr3sy']
[2024-05-04T16:21:45.867+0000] {standard_task_runner.py:91} INFO - Job 115: Subtask check_space
[2024-05-04T16:21:45.887+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.check_space manual__2024-05-04T15:57:32.696548+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T16:21:45.920+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='check_space' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T15:57:32.696548+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T15:57:32.696548+00:00'
[2024-05-04T16:21:45.921+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T16:21:45.933+0000] {logging_mixin.py:188} INFO - Insufficient disk space.
[2024-05-04T16:21:45.933+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T16:21:45.934+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_mysql.py", line 36, in chk_space
    return 1/0
           ~^~
ZeroDivisionError: division by zero
[2024-05-04T16:21:45.938+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_space, task_id=check_space, execution_date=20240504T155732, start_date=20240504T162145, end_date=20240504T162145
[2024-05-04T16:21:45.943+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 115 for task check_space (division by zero; 3693)
[2024-05-04T16:21:45.970+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-04T16:21:45.981+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T16:21:45.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
