[2024-05-15T10:15:45.582+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T10:15:45.595+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-15T10:15:45.599+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-10T00:00:00+00:00 [queued]>
[2024-05-15T10:15:45.600+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-15T10:15:45.606+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch> on 2024-05-10 00:00:00+00:00
[2024-05-15T10:15:45.610+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T10:15:45.612+0000] {standard_task_runner.py:63} INFO - Started process 315 to run task
[2024-05-15T10:15:45.611+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_hdfs', 'fetch', 'scheduled__2024-05-10T00:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/hdfs_dag.py', '--cfg-path', '/tmp/tmpmie2z4kq']
[2024-05-15T10:15:45.613+0000] {standard_task_runner.py:91} INFO - Job 163: Subtask fetch
[2024-05-15T10:15:45.644+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_hdfs.fetch scheduled__2024-05-10T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-15T10:15:45.693+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_hdfs' AIRFLOW_CTX_TASK_ID='fetch' AIRFLOW_CTX_EXECUTION_DATE='2024-05-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-10T00:00:00+00:00'
[2024-05-15T10:15:45.694+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T10:15:45.702+0000] {logging_mixin.py:188} INFO - Error reading file from HDFS: /bin/sh: 1: hadoop: Permission denied
[2024-05-15T10:15:45.703+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-15T10:15:45.703+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T10:15:45.708+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_hdfs, task_id=fetch, execution_date=20240510T000000, start_date=20240515T101545, end_date=20240515T101545
[2024-05-15T10:15:45.755+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-15T10:15:45.766+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T10:15:45.767+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
