[2024-05-16T11:24:45.797+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:24:45.835+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 manual__2024-05-16T11:24:45.374238+00:00 [queued]>
[2024-05-16T11:24:45.843+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 manual__2024-05-16T11:24:45.374238+00:00 [queued]>
[2024-05-16T11:24:45.844+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:24:45.871+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-16 11:24:45.374238+00:00
[2024-05-16T11:24:45.900+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=689) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:24:45.901+0000] {standard_task_runner.py:63} INFO - Started process 699 to run task
[2024-05-16T11:24:45.892+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'manual__2024-05-16T11:24:45.374238+00:00', '--job-id', '476', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpv96e9fah']
[2024-05-16T11:24:45.912+0000] {standard_task_runner.py:91} INFO - Job 476: Subtask import_table2
[2024-05-16T11:24:46.011+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 manual__2024-05-16T11:24:45.374238+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:24:46.168+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-16T11:24:45.374238+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-16T11:24:45.374238+00:00'
[2024-05-16T11:24:46.173+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:24:46.206+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:24:46.227+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:24:46.256+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:24:46.403+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:24:46.409+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:24:46.485+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240516T112445, start_date=20240516T112445, end_date=20240516T112446
[2024-05-16T11:24:46.519+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:24:46.578+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:24:46.585+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
