[2024-05-15T11:48:38.222+0000] {processor.py:161} INFO - Started process (PID=601) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:48:38.224+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:48:38.226+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:48:38.226+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:48:38.233+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:48:38.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:48:38.234+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:48:38.250+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.035 seconds
[2024-05-15T11:49:08.635+0000] {processor.py:161} INFO - Started process (PID=617) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:08.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:49:08.638+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:49:08.638+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:08.643+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:49:08.642+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:49:08.643+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:08.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.032 seconds
[2024-05-15T11:49:39.048+0000] {processor.py:161} INFO - Started process (PID=633) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:39.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:49:39.051+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:49:39.051+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:39.057+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:49:39.056+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:49:39.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:49:39.077+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.036 seconds
[2024-05-15T11:50:09.459+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:09.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:50:09.462+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:50:09.462+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:09.467+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:50:09.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:50:09.468+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:09.488+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.036 seconds
[2024-05-15T11:50:39.850+0000] {processor.py:161} INFO - Started process (PID=664) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:39.851+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:50:39.854+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:50:39.853+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:39.859+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:50:39.858+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:50:39.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:50:39.877+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.035 seconds
[2024-05-15T11:51:10.238+0000] {processor.py:161} INFO - Started process (PID=680) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:10.240+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:51:10.242+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:51:10.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:10.247+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:51:10.246+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:51:10.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:10.269+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.038 seconds
[2024-05-15T11:51:40.670+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:40.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:51:40.672+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:51:40.672+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:40.675+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:51:40.674+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:51:40.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:51:40.691+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.027 seconds
[2024-05-15T11:52:11.084+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:11.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:52:11.087+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:52:11.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:11.091+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:52:11.090+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:52:11.092+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:11.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.028 seconds
[2024-05-15T11:52:41.403+0000] {processor.py:161} INFO - Started process (PID=728) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:41.404+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:52:41.406+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:52:41.406+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:41.411+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:52:41.410+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:52:41.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:52:41.429+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.032 seconds
[2024-05-15T11:53:11.745+0000] {processor.py:161} INFO - Started process (PID=744) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:11.746+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:53:11.748+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:53:11.747+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:11.753+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:53:11.752+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:53:11.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:11.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.035 seconds
[2024-05-15T11:53:42.126+0000] {processor.py:161} INFO - Started process (PID=759) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:42.127+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:53:42.128+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:53:42.128+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:42.135+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:53:42.133+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:53:42.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:53:42.147+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.025 seconds
[2024-05-15T11:54:12.369+0000] {processor.py:161} INFO - Started process (PID=775) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:12.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:54:12.371+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:54:12.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:12.373+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:54:12.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:54:12.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:12.383+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.016 seconds
[2024-05-15T11:54:42.717+0000] {processor.py:161} INFO - Started process (PID=791) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:42.718+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:54:42.719+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:54:42.719+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:42.722+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:54:42.721+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:54:42.722+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:54:42.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.020 seconds
[2024-05-15T11:55:13.122+0000] {processor.py:161} INFO - Started process (PID=807) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:13.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:55:13.126+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:55:13.126+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:13.132+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:55:13.130+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:55:13.132+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:13.149+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.034 seconds
[2024-05-15T11:55:43.466+0000] {processor.py:161} INFO - Started process (PID=822) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:43.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:55:43.468+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:55:43.468+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:43.470+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:55:43.470+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:55:43.471+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:55:43.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.017 seconds
[2024-05-15T11:56:13.829+0000] {processor.py:161} INFO - Started process (PID=838) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:13.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:56:13.832+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:56:13.832+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:13.838+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:56:13.836+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:56:13.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:13.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.036 seconds
[2024-05-15T11:56:44.252+0000] {processor.py:161} INFO - Started process (PID=854) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:44.253+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:56:44.255+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:56:44.255+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:44.261+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:56:44.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:56:44.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:56:44.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.037 seconds
[2024-05-15T11:57:14.604+0000] {processor.py:161} INFO - Started process (PID=870) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:14.605+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:57:14.606+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:57:14.606+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:14.610+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:57:14.609+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:57:14.610+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:14.623+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.022 seconds
[2024-05-15T11:57:44.933+0000] {processor.py:161} INFO - Started process (PID=886) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:44.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:57:44.937+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:57:44.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:44.942+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:57:44.941+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:57:44.943+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:57:44.961+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.036 seconds
[2024-05-15T11:58:15.269+0000] {processor.py:161} INFO - Started process (PID=902) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:15.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:58:15.272+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:58:15.271+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:15.274+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:58:15.274+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:58:15.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:15.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.021 seconds
[2024-05-15T11:58:45.618+0000] {processor.py:161} INFO - Started process (PID=918) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:45.619+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:58:45.621+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:58:45.621+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:45.626+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:58:45.625+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:58:45.626+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:58:45.643+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.032 seconds
[2024-05-15T11:59:15.973+0000] {processor.py:161} INFO - Started process (PID=934) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:15.974+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:59:15.975+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:59:15.975+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:15.978+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:59:15.977+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:59:15.978+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:15.988+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.018 seconds
[2024-05-15T11:59:46.261+0000] {processor.py:161} INFO - Started process (PID=949) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:46.262+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T11:59:46.264+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:59:46.263+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:46.269+0000] {logging_mixin.py:188} INFO - [2024-05-15T11:59:46.267+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T11:59:46.269+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T11:59:46.287+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.032 seconds
[2024-05-15T12:00:16.661+0000] {processor.py:161} INFO - Started process (PID=965) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:16.663+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:00:16.665+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:00:16.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:16.672+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:00:16.670+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T12:00:16.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:16.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.040 seconds
[2024-05-15T12:00:46.979+0000] {processor.py:161} INFO - Started process (PID=981) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:46.979+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:00:46.981+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:00:46.980+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:46.983+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:00:46.983+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dag_hdfs.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_hdfs.py", line 2, in <module>
    from airflow.contrib.sensors.fs_sensor import HdfsSensor
ModuleNotFoundError: No module named 'airflow.contrib.sensors.fs_sensor'
[2024-05-15T12:00:46.984+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:00:46.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.018 seconds
[2024-05-15T12:01:17.264+0000] {processor.py:161} INFO - Started process (PID=997) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:17.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:01:17.269+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:01:17.268+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:17.272+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:01:17.271+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/dag_hdfs.py assumed to contain no DAGs. Skipping.
[2024-05-15T12:01:17.272+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:17.288+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.029 seconds
[2024-05-15T12:01:47.672+0000] {processor.py:161} INFO - Started process (PID=1013) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:47.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:01:47.674+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:01:47.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:47.676+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:01:47.676+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/dag_hdfs.py assumed to contain no DAGs. Skipping.
[2024-05-15T12:01:47.676+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:01:47.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.020 seconds
[2024-05-15T12:02:18.085+0000] {processor.py:161} INFO - Started process (PID=1029) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:18.086+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:02:18.087+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:02:18.087+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:18.088+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:02:18.088+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/dag_hdfs.py assumed to contain no DAGs. Skipping.
[2024-05-15T12:02:18.088+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:18.097+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.017 seconds
[2024-05-15T12:02:48.472+0000] {processor.py:161} INFO - Started process (PID=1045) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:48.473+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:02:48.475+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:02:48.475+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:48.477+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:02:48.477+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/dag_hdfs.py assumed to contain no DAGs. Skipping.
[2024-05-15T12:02:48.478+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:02:48.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.027 seconds
[2024-05-15T12:03:18.855+0000] {processor.py:161} INFO - Started process (PID=1061) to work on /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:03:18.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_hdfs.py for tasks to queue
[2024-05-15T12:03:18.857+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:03:18.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:03:18.858+0000] {logging_mixin.py:188} INFO - [2024-05-15T12:03:18.858+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/dag_hdfs.py assumed to contain no DAGs. Skipping.
[2024-05-15T12:03:18.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_hdfs.py
[2024-05-15T12:03:18.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_hdfs.py took 0.017 seconds
