[2024-05-04T16:14:33.399+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-04T16:14:33.412+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_space.dump_fc_account_master manual__2024-05-04T15:57:32.696548+00:00 [queued]>
[2024-05-04T16:14:33.416+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_space.dump_fc_account_master manual__2024-05-04T15:57:32.696548+00:00 [queued]>
[2024-05-04T16:14:33.416+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 7
[2024-05-04T16:14:33.421+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): dump_fc_account_master> on 2024-05-04 15:57:32.696548+00:00
[2024-05-04T16:14:33.424+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3325) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-04T16:14:33.425+0000] {standard_task_runner.py:63} INFO - Started process 3326 to run task
[2024-05-04T16:14:33.424+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_space', 'dump_fc_account_master', 'manual__2024-05-04T15:57:32.696548+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpplwdh7o9']
[2024-05-04T16:14:33.426+0000] {standard_task_runner.py:91} INFO - Job 109: Subtask dump_fc_account_master
[2024-05-04T16:14:33.447+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_space.dump_fc_account_master manual__2024-05-04T15:57:32.696548+00:00 [running]> on host f85b7a0b58b5
[2024-05-04T16:14:33.482+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_space' AIRFLOW_CTX_TASK_ID='dump_fc_account_master' AIRFLOW_CTX_EXECUTION_DATE='2024-05-04T15:57:32.696548+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-04T15:57:32.696548+00:00'
[2024-05-04T16:14:33.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-04T16:14:33.489+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-04T16:14:33.489+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        mysqldump -h host.docker.internal -u root --password=12345678 client_rw fc_account_master > /opt/***/dags/first.sql\n        ']
[2024-05-04T16:14:33.492+0000] {subprocess.py:86} INFO - Output:
[2024-05-04T16:14:33.551+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-04T16:14:33.552+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-04T16:14:33.564+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_space, task_id=dump_fc_account_master, execution_date=20240504T155732, start_date=20240504T161433, end_date=20240504T161433
[2024-05-04T16:14:33.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-04T16:14:33.621+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-04T16:14:33.623+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
