[2024-05-15T10:15:44.236+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T10:15:44.268+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-06T00:00:00+00:00 [queued]>
[2024-05-15T10:15:44.274+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_hdfs.fetch scheduled__2024-05-06T00:00:00+00:00 [queued]>
[2024-05-15T10:15:44.275+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-15T10:15:44.283+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): fetch> on 2024-05-06 00:00:00+00:00
[2024-05-15T10:15:44.291+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_hdfs', 'fetch', 'scheduled__2024-05-06T00:00:00+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/hdfs_dag.py', '--cfg-path', '/tmp/tmp6lv85er0']
[2024-05-15T10:15:44.295+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=270) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T10:15:44.298+0000] {standard_task_runner.py:63} INFO - Started process 290 to run task
[2024-05-15T10:15:44.296+0000] {standard_task_runner.py:91} INFO - Job 158: Subtask fetch
[2024-05-15T10:15:44.352+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_hdfs.fetch scheduled__2024-05-06T00:00:00+00:00 [running]> on host f85b7a0b58b5
[2024-05-15T10:15:44.417+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_hdfs' AIRFLOW_CTX_TASK_ID='fetch' AIRFLOW_CTX_EXECUTION_DATE='2024-05-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-06T00:00:00+00:00'
[2024-05-15T10:15:44.421+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T10:15:44.439+0000] {logging_mixin.py:188} INFO - Error reading file from HDFS: /bin/sh: 1: hadoop: Permission denied
[2024-05-15T10:15:44.440+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-15T10:15:44.442+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T10:15:44.453+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_hdfs, task_id=fetch, execution_date=20240506T000000, start_date=20240515T101544, end_date=20240515T101544
[2024-05-15T10:15:44.488+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-15T10:15:44.498+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T10:15:44.501+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
