[2024-05-16T11:19:49.449+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:19:49.486+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:19:49.492+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:19:49.494+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:19:49.563+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-11 00:00:00+00:00
[2024-05-16T11:19:49.574+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=265) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:19:49.570+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '404', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpnii95j65']
[2024-05-16T11:19:49.581+0000] {standard_task_runner.py:91} INFO - Job 404: Subtask import_table2
[2024-05-16T11:19:49.578+0000] {standard_task_runner.py:63} INFO - Started process 278 to run task
[2024-05-16T11:19:49.623+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:19:49.727+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-16T11:19:49.729+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:19:49.740+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:19:49.741+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql;\n                ']
[2024-05-16T11:19:49.756+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:19:49.922+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:19:49.925+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:19:49.959+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240511T000000, start_date=20240516T111949, end_date=20240516T111949
[2024-05-16T11:19:49.994+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:19:50.019+0000] {taskinstance.py:3482} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:19:50.028+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:22:31.966+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:22:31.998+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:22:32.011+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:22:32.015+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:22:32.034+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-11 00:00:00+00:00
[2024-05-16T11:22:32.044+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '458', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpsl1goblq']
[2024-05-16T11:22:32.054+0000] {standard_task_runner.py:91} INFO - Job 458: Subtask import_table2
[2024-05-16T11:22:32.051+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=539) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:22:32.064+0000] {standard_task_runner.py:63} INFO - Started process 555 to run task
[2024-05-16T11:22:32.103+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:22:32.167+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-16T11:22:32.168+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:22:32.178+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:22:32.180+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:22:32.190+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:22:32.276+0000] {subprocess.py:93} INFO - ERROR 1146 (42S02) at line 41: Table 'test.product_category' doesn't exist
[2024-05-16T11:22:32.278+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-05-16T11:22:32.280+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:22:32.294+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-05-16T11:22:32.299+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_tables, task_id=import_table2, execution_date=20240511T000000, start_date=20240516T112232, end_date=20240516T112232
[2024-05-16T11:22:32.309+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 458 for task import_table2 (Bash command failed. The command returned a non-zero exit code 1.; 555)
[2024-05-16T11:22:32.333+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-16T11:22:32.350+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:22:32.350+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-05-16T11:24:49.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-16T11:24:49.749+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:24:49.759+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [queued]>
[2024-05-16T11:24:49.762+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-05-16T11:24:49.794+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): import_table2> on 2024-05-11 00:00:00+00:00
[2024-05-16T11:24:49.802+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=771) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-16T11:24:49.804+0000] {standard_task_runner.py:63} INFO - Started process 781 to run task
[2024-05-16T11:24:49.803+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_tables', 'import_table2', 'scheduled__2024-05-11T00:00:00+00:00', '--job-id', '499', '--raw', '--subdir', 'DAGS_FOLDER/dag_mysql.py', '--cfg-path', '/tmp/tmpaxig5uf8']
[2024-05-16T11:24:49.810+0000] {standard_task_runner.py:91} INFO - Job 499: Subtask import_table2
[2024-05-16T11:24:49.844+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_tables.import_table2 scheduled__2024-05-11T00:00:00+00:00 [running]> on host 7084a6d88d3b
[2024-05-16T11:24:49.910+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='bses' AIRFLOW_CTX_DAG_ID='dag_tables' AIRFLOW_CTX_TASK_ID='import_table2' AIRFLOW_CTX_EXECUTION_DATE='2024-05-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-11T00:00:00+00:00'
[2024-05-16T11:24:49.912+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-16T11:24:49.923+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-05-16T11:24:49.924+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n                mysql -h host.docker.internal -u root --password=12345678 test < /opt/***/dags/product_category.sql\n                ']
[2024-05-16T11:24:49.936+0000] {subprocess.py:86} INFO - Output:
[2024-05-16T11:24:50.040+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-05-16T11:24:50.044+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-16T11:24:50.063+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=dag_tables, task_id=import_table2, execution_date=20240511T000000, start_date=20240516T112449, end_date=20240516T112450
[2024-05-16T11:24:50.109+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-16T11:24:50.119+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-16T11:24:50.121+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
